#ifndef CUP_CONSTANTS_H
#define CUP_CONSTANTS_H

// IN-MEMORY STATE CAPACITY
#define MAX_INSTALLED 32
#define MAX_DEFAULTS 6

// GENERIC BUFFER SIZE
#define MAX_NAME_LEN 32
#define MAX_ENTRY_LEN 64
#define MAX_PLATFORM_LEN 64
#define MAX_PATH_LEN 1024

// STATE FILE
#define MAX_STATE_LINE_LEN 128

// MANIFEST FILE
#define MAX_MANIFEST_LINE_LEN 1024
#define MAX_MANIFEST_KEY_LEN 128
#define MAX_MANIFEST_VALUE_LEN 256
#define MAX_MANIFEST_URL_LEN 896

#endif /* CUP_CONSTANTS_H */