#ifndef CUP_ERROR_H
#define CUP_ERROR_H

typedef enum {
    CUP_OK = 0,

    // INPUT / CLI
    CUP_ERR_INVALID_INPUT,

    // SUPPORTED DOMAIN
    CUP_ERR_UNSUPPORTED_COMPONENT,
    CUP_ERR_INVALID_TOOL,
    CUP_ERR_INVALID_RELEASE,
    CUP_ERR_INVALID_OS,
    CUP_ERR_INVALID_ARCH,
    CUP_ERR_NOT_AVAILABLE,

    // MANIFEST
    CUP_ERR_MANIFEST,

    // STATE
    CUP_ERR_STATE_LOAD,
    CUP_ERR_STATE_SAVE,
    CUP_ERR_STATE_FULL,
    CUP_ERR_DEFAULT_FULL,
    CUP_ERR_ALREADY_INSTALLED,
    CUP_ERR_NOT_INSTALLED,
    CUP_ERR_INCONSISTENT_STATE,

    // FILESYSTEM / TEMPORARY STORAGE
    CUP_ERR_FILESYSTEM,
    CUP_ERR_TEMPORARY,

    // PACKAGE TRANSFER / ARCHIVES
    CUP_ERR_FETCH,
    CUP_ERR_ARCHIVE,
    CUP_ERR_EXTRACT,

    // INSTALL VALIDATION / TRANSACTIONS
    CUP_ERR_VALIDATION,
    CUP_ERR_COMMIT,
    CUP_ERR_ROLLBACK,

    // INTERRUPT
    CUP_ERR_INTERRUPT
} CupError;

#endif /* CUP_ERROR_H */