#ifndef CUP_ERROR_H
#define CUP_ERROR_H

typedef enum {
    CUP_OK = 0,

    // GENERIC INPUT / VALIDATION
    CUP_ERR_INVALID_INPUT,
    CUP_ERR_UNSUPPORTED_COMPONENT,
    CUP_ERR_INVALID_TOOL,
    CUP_ERR_INVALID_RELEASE,

    // PERSISTENT STATE
    CUP_ERR_STATE_LOAD,
    CUP_ERR_STATE_SAVE,
    CUP_ERR_STATE_FULL,
    CUP_ERR_DEFAULT_FULL,
    CUP_ERR_ALREADY_INSTALLED,
    CUP_ERR_NOT_INSTALLED,
    CUP_ERR_INCONSISTENT_STATE,

    // FILESYSTEM / TEMPORARY STORAGE
    CUP_ERR_FS,
    CUP_ERR_TMP,

    // INSTALL/REMOVE OPERATIONS
    CUP_ERR_FETCH,
    CUP_ERR_INSTALL,
    CUP_ERR_VALIDATION,
    CUP_ERR_COMMIT,
    CUP_ERR_ROLLBACK,
    CUP_ERR_INTERRUPT
} CupError;

#endif /* CUP_ERROR_H */