#ifndef ERROR_H
#define ERROR_H

typedef enum {
    CUP_OK = 0,
    CUP_ERR_INVALID_INPUT,
    CUP_ERR_UNSUPPORTED_COMPONENT,
    CUP_ERR_ALREADY_INSTALLED,
    CUP_ERR_NOT_INSTALLED,
    CUP_ERR_INCONSISTENT_STATE,
    CUP_ERR_STATE_LOAD,
    CUP_ERR_STATE_SAVE,
    CUP_ERR_STATE_FULL,
    CUP_ERR_DEFAULT_FULL,
    CUP_ERR_FS,
    CUP_ERR_TMP,
    CUP_ERR_VALIDATION,
    CUP_ERR_COMMIT,
    CUP_ERR_ROLLBACK,
    CUP_ERR_INTERRUPT,
    CUP_ERR_INVALID_TOOL,
    CUP_ERR_INVALID_RELEASE,
    CUP_ERR_FETCH,
    CUP_ERR_INSTALL,
    CUP_ERR_RESOLVE_RELEASE
} CupError;

#endif